defaults:
  - env/libero_spatial@env.train
  - env/libero_spatial@env.eval
  - model/pi0_5@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor,env,rollout: 0-1

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "libero_spatial_grpo_openpi_pi05_eval_nc20"
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 1
  max_steps: -1

  only_eval: True
  val_check_interval: -1
  save_interval: 25

  resume_dir: null
  ckpt_path: null
  # ckpt_path: "/mnt/43t/wxh/RLinf/logs/20260128-09:36:02-libero_spatial_grpo_openpi_pi05/libero_spatial_grpo_openpi_pi05/checkpoints/global_step_240/actor/model_state_dict/full_weights.pt"

algorithm:
  normalize_advantages: True
  kl_penalty: kl
  group_size: 2
  reward_coef: 1.0
  use_eff_reward: False
  eff_reward_coef: 1.0
  eff_max_step: 150
  use_temporal_stability_penalty: False
  temporal_stability_coef: 0.15
  use_plan_reward: True
  plan_reward_coef: 1.0
  plan_reward_base_h: 20

  rollout_epoch: 8
  eval_rollout_epoch: 10

  reward_type: chunk_level
  logprob_type: chunk_level
  entropy_type: token_level
  update_epoch: 1

  adv_type: grpo
  loss_type: actor
  loss_agg_func: "token-mean"
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.2
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0

  gamma: 0.99
  gae_lambda: 0.95

  filter_rewards: True
  rewards_lower_bound: 0.1
  rewards_upper_bound: 1.0
  sampling_params:
    do_sample: True
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0
    add_BOS: False

  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  enable_offload: False

  train:
    total_num_envs: 64
    group_size: ${algorithm.group_size}
    max_episode_steps: 160
    max_steps_per_rollout_epoch: 160
  eval:
    total_num_envs: 50
    use_ordered_reset_state_ids: True
    auto_reset: True
    ignore_terminations: True
    max_episode_steps: 240
    max_steps_per_rollout_epoch: 240
    group_size: 1
    is_eval: True
    video_cfg:
      save_video: True
      video_base_dir: ${runner.logger.log_path}/video/eval

rollout:
  group_name: "RolloutGroup"
  generation_backend: "huggingface"
  recompute_logprobs: False
  unnorm_key: libero_10
  enable_offload: False
  pipeline_stage_num: 1
  plan_horizon: 15
  action_horizons_pattern: [15, 10, 5]

  model:
    model_path: "/mnt/43t/wxh/RLinf/models/RLinf-Pi05-PPO-LIBERO-130"
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 128
  global_batch_size: 2048
  seed: 42
  enable_offload: False

  model:
    model_path: "/mnt/43t/wxh/RLinf/models/RLinf-Pi05-PPO-LIBERO-130"
    num_action_chunks: 20
    num_steps: 3
    openpi:
      action_horizon: 20

  optim:
    lr: 5.0e-6
    value_lr: 1.0e-4
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    weight_decay: 0.01
    clip_grad: 1.0

  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "no_shard"
    gradient_checkpointing: False
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False
